# PVC for website
# I use https://github.com/rancher/local-path-provisioner, you probably have to configure storageClassName accordingly
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ef-old-website-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi